services:
  db:
    image: postgres:17
    container_name: attendr_postgres
    restart: always
    env_file:
      - .env.local
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=attendr
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: attendr_redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  pgdata:
