name: DB Migration

on:
  push:
    branches: [dev, main]
    paths: ['prisma/**']

permissions:
  contents: read

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Install Pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 25
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Dev Database Sync
        if: github.ref == 'refs/heads/dev'
        env: { DATABASE_URL: '${{ secrets.DEV_DATABASE_URL }}' }
        run: pnpm prisma db push

      - name: Prod Database Deploy
        if: github.ref == 'refs/heads/main'
        env: { DATABASE_URL: '${{ secrets.PROD_DATABASE_URL }}' }
        run: pnpm prisma migrate deploy
